### ISSUE TITLE
How to start it

### ISSUE THREAD

**Issue by BlueAkoasm** [christopherdoer/rrxio#1]
`SUMMARY
========

CLEAR PARAMETERS
 * /rrxio/

PARAMETERS
 * /odom_to_path_rrxio_visual/filter_name: RRxIO Visual
 * /odom_to_path_rrxio_visual/topic_odom: /rrxio/rovio/odom...
 * /plot_states_uncertainty/topic_prefix: /rrxio/rovio/
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /rrxio/N_ransac_points: 3
 * /rrxio/allowed_outlier_percentage: 0.25
 * /rrxio/azimuth_thresh_deg: 60
 * /rrxio/bag_dur: 10000
 * /rrxio/bag_start: 0
 * /rrxio/cam0_topic_name: /sensor_platform/...
 * /rrxio/cam1_topic_name: cam1_not_used
 * /rrxio/camera0_config: /home/linux/datab...
 * /rrxio/camera_frame: camera
 * /rrxio/elevation_thresh_deg: 60
 * /rrxio/filter_config: /home/linux/catki...
 * /rrxio/filter_max_z: 100
 * /rrxio/filter_min_z: -100
 * /rrxio/imu_frame: base_link
 * /rrxio/imu_topic_name: /sensor_platform/imu
 * /rrxio/inlier_thresh: 0.25
 * /rrxio/l_b_r_x: 0.0
 * /rrxio/l_b_r_y: 0.03
 * /rrxio/l_b_r_z: 0.06
 * /rrxio/max_dist: 100
 * /rrxio/max_frame_ctr: 2000000
 * /rrxio/max_r_cond: 1000
 * /rrxio/max_sigma_x: 0.5
 * /rrxio/max_sigma_y: 0.5
 * /rrxio/max_sigma_z: 0.5
 * /rrxio/min_db: 5
 * /rrxio/min_dist: 0.25
 * /rrxio/outlier_prob: 0.4
 * /rrxio/q_b_r_w: 0.00524
 * /rrxio/q_b_r_x: 0.69946
 * /rrxio/q_b_r_y: 0.71461
 * /rrxio/q_b_r_z: 0.00723
 * /rrxio/radar_velocity_correction_factor: 1.0
 * /rrxio/rosbag_filename: /home/linux/datab...
 * /rrxio/sigma_offset_radar_x: 0.1
 * /rrxio/sigma_offset_radar_y: 0.05
 * /rrxio/sigma_offset_radar_z: 0.1
 * /rrxio/sigma_v_d: 0.125
 * /rrxio/sigma_zero_velocity_x: 0.025
 * /rrxio/sigma_zero_velocity_y: 0.025
 * /rrxio/sigma_zero_velocity_z: 0.025
 * /rrxio/success_prob: 0.999999
 * /rrxio/thresh_zero_velocity: 0.05
 * /rrxio/timeshift_cam_imu: -0.004
 * /rrxio/topic_radar_scan: /sensor_platform/...
 * /rrxio/topic_radar_trigger: /sensor_platform/...
 * /rrxio/topic_vel: not_used
 * /rrxio/use_cholesky_instead_of_bdcsvd: True
 * /rrxio/use_odr: True
 * /rrxio/use_ransac: True
 * /rrxio/world_frame: odom

NODES
  /
    odom_to_path_rrxio_visual (rrxio/odom_to_path.py)
    plot_states_uncertainty (rrxio/plot_states_uncertainty.py)
    rrxio (rrxio/rrxio_rosbag_loader_10)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[rrxio-1]: started with pid [4360]
process[odom_to_path_rrxio_visual-2]: started with pid [4362]
process[plot_states_uncertainty-3]: started with pid [4363]
process[rviz-4]: started with pid [4364]
[ INFO] [1656057227.880663612]: RRxIO started`

Hello, i successfully run the code using 
`roslaunch rrxio rrxio_thermal_iros_demo.launch rosbag_dir:=/home/linux/database/irs_rtvi rosbag:=outdoor_street N:=10`
but nothing happened, the terminal stuck at "RRxIO started"
what should i do? Did i do somthing wrong？How can i start the VIO?

**Comment by christopherdoer** [comment]
Hi,
Thanks for checking out RRxIO ;) any progress? 
I've never tried RRxIO with ROS Melodic - I will check it out the upcoming days.
Best,
Chris

**Comment by li-peize** [comment]
Hi Chris,
I'm trying this repo on ROS Melodic as well. 
I got past the 'RRxIO started' message. 
But after the message, I got:
`[RadarEgoVelocityEstimator]: Zero velocity detected!`
followed by:
`[radarScanCallback]: Ego velocity failed`
And the `/odometry` and `/pose` didn't publish any messages.
A colleague tried on a Kinetic docker environment and got the same results.

Here is the full output:
[out.txt](https://github.com/christopherdoer/rrxio/files/9020880/out.txt)

Best,
Peize

**Comment by christopherdoer** [comment]
@BlueAkoasm  thanks for opening the issue, hopefully I was able to resolve it!
@li-peize actually you should see the odometry under `rostopic echo /rrxio/rovio/odometry`, the ego velocity failed all the time due a parameter bug in REVE...

Can you do me a favor and try out the branch [feature_fixes_startup_melodic](https://github.com/christopherdoer/rrxio/tree/feature_fixes_startup_melodic)?   
Make sure to run `git submodule update --init --recursive` because the bug was actually loacated in REVE.
In addition, I fixed the CMakeLists such that it builds the rosbag_nodes for N=10,15,25. Building on all cores might cause issues with too much RAM usage --> build with `catkin build rrxio -j2 --cmake-args -DCMAKE_BUILD_TYPE=Release` worked for me.

Thanks!

**Comment by li-peize** [comment]
Hi Chris, 
Thanks for the timely update. The new branch works perfectly!

**Comment by BlueAkoasm** [comment]
> @BlueAkoasm thanks for opening the issue, hopefully I was able to resolve it! @li-peize actually you should see the odometry under `rostopic echo /rrxio/rovio/odometry`, the ego velocity failed all the time due a parameter bug in REVE...
> 
> Can you do me a favor and try out the branch [feature_fixes_startup_melodic](https://github.com/christopherdoer/rrxio/tree/feature_fixes_startup_melodic)? Make sure to run `git submodule update --init --recursive` because the bug was actually loacated in REVE. In addition, I fixed the CMakeLists such that it builds the rosbag_nodes for N=10,15,25. Building on all cores might cause issues with too much RAM usage --> build with `catkin build rrxio -j2 --cmake-args -DCMAKE_BUILD_TYPE=Release` worked for me.
> 
> Thanks!

Thanks for your reply! I will try it later!

**Comment by BlueAkoasm** [comment]
@christopherdoer Thanks for your reply! I will try it later!
